language: python
python:
    - "2.7"

# command to install dependencies
install:
    - 'pip install coveralls --use-mirrors'
    - 'pip install -r requirements.txt --use-mirrors'
    - 'python setup.py install'

script:
    - tox -v
